### ISSUE TITLE
[FTL] The system cannot find the file specified.  (GitHub Actions Windows Docker)

### ISSUE THREAD

**Issue by altendky** [codecov/codecov-exe#119]
```
[FTL] The system cannot find the file specified.
```

What file is missing?  How do I fix it?  This is on GitHub Actions in Windows running a Windows Docker guest.

https://github.com/altendky/qtrio/pull/42/checks?check_run_id=816428818
```
DEBUG:   27+  >>>> ./codecov.exe -n "$Env:JOB_NAME"
   [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCh 
   ildItemCommand
 

            _____          _
            / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
            \_____\___/ \____|\___|\___\___/ \_/
                                        exe-1.12.0
            
GitHubAction detected.
[FTL] The system cannot find the file specified.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Codecov.Terminal.Terminal.Run(String command, String commandArguments)
   at Codecov.Services.VersionControlSystems.Git.LoadDetecter()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Codecov.Services.VersionControlSystems.Git.get_Detecter()
   at Codecov.Factories.VersionControlSystemFactory.GetFirstDetectedVcsSystem(IEnumerable`1 supportedVcs, IVersionControlSystemOptions options, ITerminal terminal)
   at Codecov.Factories.VersionControlSystemFactory.Create(IVersionControlSystemOptions options, ITerminal terminal)
   at Codecov.Program.UploadFacade.get_VersionControlSystem()
   at Codecov.Program.UploadFacade.Uploader()
   at Codecov.Program.Run.Uploader()
   at Codecov.Program.Run.Runner(IEnumerable`1 args)
```

**Comment by AdmiringWorm** [comment]
Is `./codecov.exe -n "$Env:JOB_NAME"` exactly how `codecov-exe` is called?
If so, then what you actually are missing is a path to the files that you wish to upload.
Unlike the bash uploader, this uploader do not keep an internal list of default files to check.

use the `-f` argument for specifying which files to upload (globbing is also supported, as long as you make sure the paths are quoted with `"`)

**Comment by AdmiringWorm** [comment]
Closing due to lack of response.
Feel free to ask to re-open when/if you can provide additional information.

**Comment by altendky** [comment]
@AdmiringWorm, my apologies for missing your response.  I think the follow-up would be that reporting an inability to find a file I didn't specify and for which there are no defaults isn't the most obvious error.  `:]`  I am using the bash uploader now and I think it is the recommended one and is working well.  Thank you for the explanation.

**Comment by AdmiringWorm** [comment]
> I think the follow-up would be that reporting an inability to find a file I didn't specify and for which there are no defaults isn't the most obvious error.

I agree entirely, and I thought we did some validation on that part.
But it seems we only validate when a file(s) is specified.

> I am using the bash uploader now, and I think it is the recommended one and is working well.

Indeed, it is the recommended one, and the only one officially supported (everything else is considered community maintained).
I prefer this community uploader, but that is only because I work on C# projects and it is supported through an addin when running cake build scripts (which won't work with codecov-bash).

Thanks for coming back with the response/feedback.
