### ISSUE TITLE
Running on azure fails due to question mark not being escaped in the `build_url` parameter

### ISSUE THREAD

**Issue by AdmiringWorm** [codecov/codecov-exe#170]
```
            _____          _
            / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
            \_____\___/ \____|\___|\___\___/ \_/
            exe-1.12.4+28c5cd57bef15ea765ee8e362a35f3d74fd9004a
AzurePipelines detected.
Git detected.
Project root: D:\a\1\s
Yaml not found, that's ok! Learn more at https://docs.codecov.io/docs/codecov-yaml
Reading reports.
D:/a/1/s/BuildArtifacts/TestCoverage/coverlet/Cake-DotNetVersionDetector-Tests.netcoreapp2.1.opencover.xml
D:/a/1/s/BuildArtifacts/TestCoverage/coverlet/Cake-DotNetVersionDetector-Tests.netcoreapp3.1.opencover.xml
Uploading Reports.
url: https://codecov.io
query: https://codecov.io/upload/v4?branch=develop&commit=9fd94852e15f259eb6ec0dd16f30758d0a4ca778&build=20210215.3&tag=&pr=&name=&flags=&slug=cake-contrib%2FCake.DotNetVersionDetector&token=&package=exe-1.12.4+28c5cd57bef15ea765ee8e362a35f3d74fd9004a&build_url=https://dev.azure.com/cake-contrib/Cake.DotNetVersionDetector/_build/results?buildId=5691&yaml=&job=5691&service=azure_pipelines&project=Cake.DotNetVersionDetector&server_uri=https://dev.azure.com/cake-contrib/
Pinging Codecov
[WRN] Unable to upload coverage report to Codecov. Server returned: (400) Bad Request
[WRN] Unable to upload coverage report to Codecov. Server returned: (400) Bad Request
[WRN] HTTP 400
Build numbers do not match. Please upload with the Codecov repository upload token to resolve issue.
Uploading to Codecov
[WRN] Unable to upload coverage report to Codecov. Server returned: (400) Bad Request
[WRN] Unable to upload coverage report to Codecov. Server returned: (400) Bad Request
[WRN] HTTP 400
Build numbers do not match. Please upload with the Codecov repository upload token to resolve issue.
[WRN] Failed to upload the report with CodecovFallbackUploader.
[FTL] Failed to upload the report.
Codecov.Exceptions.UploadException: Failed to upload the report.
   at Codecov.Upload.Uploads.Uploader() in /_/Source/Codecov/Upload/Uploads.cs:line 35
   at Codecov.Program.UploadFacade.Uploader() in /_/Source/Codecov/Program/UploadFacade.cs:line 132
```

**Comment by AdmiringWorm** [comment]
question marks should be url encoded to `%3F` to prevent the failure to happen.
