### ISSUE TITLE
Bad request (400) with non-standard branch name

### ISSUE THREAD

**Issue by kalaider** [codecov/codecov-exe#32]
If the branch name starts with `#` symbol, e.g. `#8-move-docs`, `codecov.exe` returns 400. (In git bash such branch names must be quoted: `git checkout "#8-move-docs"`.)

```
codecov -f "coverage.xml"
              _____          _
             / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
             \_____\___/ \____|\___|\___\___/ \_/
                                         exe-1.0.1
            
2018-01-18 06:04:44 [Information] AppVeyor detected.
2018-01-18 06:04:44 [Information] Git detected.
2018-01-18 06:04:44 [Information] Project root: C:\projects\navigizer
2018-01-18 06:04:44 [Information] Reading reports.
2018-01-18 06:04:44 [Information] coverage.xml
2018-01-18 06:04:44 [Information] Uploading Reports.
2018-01-18 06:04:44 [Information] url: https://codecov.io
2018-01-18 06:04:44 [Information] query: https://codecov.io/upload/v4?branch=#8-move-docs&commit=aaf0e2945edfcb6c05aea89a97f3941a32ee087e&build=vyf1jnfv5cm0qpaf&tag=&pr=&name=&flags=&slug=kalaider%2FNavigizer&token=&package=exe-1.0.1&build_url=&yaml=.codecov.yml&job=kalaider%2Fnavigizer%2F21&service=appveyor
2018-01-18 06:04:44 [Information] Pinging Codecov
2018-01-18 06:04:45 [Fatal] One or more errors occurred. (The remote server returned an error: (400) Bad Request.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Codecov.Upload.Upload.Uploader() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Upload\Upload.cs:line 34
   at Codecov.Program.UploadFacade.Uploader() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Program\UploadFacade.cs:line 119
   at Codecov.Program.Run.Runner(IEnumerable`1 args) in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Program\Run.cs:line 20
```

**Comment by stevepeak** [comment]
The `#` needs to be escaped. 👍

**Comment by AdmiringWorm** [comment]
this will be fixed in the upcoming release of the next version
