### ISSUE TITLE
Failure to upload report

### ISSUE THREAD

**Issue by StanleyGoldman** [codecov/codecov-exe#43]
👋 I'm integrating codecov with for GitHub's Octokit.NET in this pull request [octokit.net#1866](https://github.com/octokit/octokit.net/pull/1866)

I'm having some trouble. Hopefully someone can point me in the right direction..

https://ci.appveyor.com/project/github-windows/octokit-net/build/0.33.0-PullRequest.1866+19.build.2876

```
2018-09-10 08:40:23 INF AppVeyor detected.
2018-09-10 08:40:23 INF Git detected.
2018-09-10 08:40:24 INF Project root: C:\projects\octokit-net
2018-09-10 08:40:24 INF Reading reports.
2018-09-10 08:40:24 INF coverage-results/Octokit.Tests-net452.xml
2018-09-10 08:40:24 INF Uploading Reports.
2018-09-10 08:40:26 INF url: https://codecov.io
2018-09-10 08:40:27 INF query: https://codecov.io/upload/v4?branch=master&commit=2257fc9d1b3d27dd778110a25cf7488bac314204&build=76nmgd4bylva7iqj&tag=&pr=1866&name=&flags=&slug=octokit%2Foctokit.net&token=&package=exe-1.0.5&build_url=&yaml=codecov.yml&job=github-windows%2Foctokit-net%2F0.17.2876&service=appveyor
2018-09-10 08:40:27 INF Pinging Codecov
2018-09-10 08:40:31 FTL Failed to upload the report.
   at Codecov.Upload.Uploads.Uploader() in D:\Docs\git\contributing\codecov-exe\Source\Codecov\Upload\Uploads.cs:line 34
   at Codecov.Program.UploadFacade.Uploader() in D:\Docs\git\contributing\codecov-exe\Source\Codecov\Program\UploadFacade.cs:line 119
   at Codecov.Program.Run.Runner(IEnumerable`1 args) in D:\Docs\git\contributing\codecov-exe\Source\Codecov\Program\Run.cs:line 20
```

**Comment by AdmiringWorm** [comment]
@StanleyGoldman from the looks of it, this is caused by the build version being changed on appveyor. Unfortunately this isn't something we can fix here, as the changed environment variable isn't available until the next line in the `appveyor.yml` file.

However, see the [Known Issues](https://github.com/cake-contrib/Cake.Codecov#known-issues) section of `Cake.Codecov` for a workaround.

**Comment by StanleyGoldman** [comment]
Hey @AdmiringWorm thanks for getting back to me. Sorry I'm taking so long to reply.

The known issues indicates that I should be restoring `APPVEYOR_BUILD_VERSION` to a known value.
But I counter that `APPVEYOR_BUILD_VERSION` seems to be correct and matches the value in other builds where codecov.exe is working.

Is there some other environment variable I should be checking?

**Comment by StanleyGoldman** [comment]
Working here: https://ci.appveyor.com/project/github-windows/octokit-graphql/build/1.0.682
```
echo %APPVEYOR_BUILD_VERSION%
1.0.682
```

Not working here: https://ci.appveyor.com/project/github-windows/octokit-net/build/0.17.2890
```
Current APPVEYOR_BUILD_VERSION: 0.17.2890
```

**Comment by StanleyGoldman** [comment]
I think I may finally understand

**Comment by StanleyGoldman** [comment]
Yep, the point is for the build numbers to match.
Thanks.

**Comment by AdmiringWorm** [comment]
> Yep, the point is for the build numbers to match.

Exactly, if you have suggestion on improving the documentation for the example shown there, then feel free to open a PR to that repo (I know I'm not the best person to explain stuff).

I hope you're able to get it to work, but feel free to contact me on gitter (link in the Readme.md file in the repo, or ask in this or the Cake.Codecov repository).
